language: python

python:
  - '2.6'
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
  - 'nightly'

before_install:
  - python -m pip install setuptools

install:
  - python -m pip install .

script:
  - python setup.py test
